# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ACS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.openGLWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.openGLWidget.setObjectName("openGLWidget")
        self.gridLayout.addWidget(self.openGLWidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Config = QtWidgets.QMenu(self.menubar)
        self.menu_Config.setObjectName("menu_Config")
        self.menuShow = QtWidgets.QMenu(self.menubar)
        self.menuShow.setObjectName("menuShow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView_2 = QtWidgets.QListView(self.dockWidgetContents_2)
        self.listView_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_2.addWidget(self.listView_2)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionACS = QtWidgets.QAction(MainWindow)
        self.actionACS.setObjectName("actionACS")
        self.actionEnviorment = QtWidgets.QAction(MainWindow)
        self.actionEnviorment.setObjectName("actionEnviorment")
        self.actionMacines = QtWidgets.QAction(MainWindow)
        self.actionMacines.setObjectName("actionMacines")
        self.menu_Config.addAction(self.actionACS)
        self.menu_Config.addAction(self.actionEnviorment)
        self.menuShow.addAction(self.actionMacines)
        self.menubar.addAction(self.menu_Config.menuAction())
        self.menubar.addAction(self.menuShow.menuAction())

        self.retranslateUi(MainWindow)
        self.actionMacines.triggered.connect(self.dockWidget_2.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Snapshot"))
        self.pushButton.setText(_translate("MainWindow", "Render"))
        self.menu_Config.setTitle(_translate("MainWindow", "&Config"))
        self.menuShow.setTitle(_translate("MainWindow", "Show"))
        self.actionACS.setText(_translate("MainWindow", "Config"))
        self.actionEnviorment.setText(_translate("MainWindow", "Overview"))
        self.actionMacines.setText(_translate("MainWindow", "Macines"))
